name: AndroidBuild
on:
  pull_request:
    branches: [master]

  push:
    branches: [master]

jobs:
  build:
    name: AndroidBuild
    runs-on: windows-latest
    permissions: read-all
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.2
        with:
          fetch-depth: 0

      - name: Setup Java JDK
        uses: actions/setup-java@v4.2.1
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Cache SonarQube packages
        uses: actions/cache@v1
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar
          restore-keys: ${{ runner.os }}-sonar

      - name: Cache Gradle packages
        uses: actions/cache@v1
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
          restore-keys: ${{ runner.os }}-gradle

      - name: Build and analyze
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
          run: ./gradlew build sonar --info

     # - name: Build with Gradle
     #   run: ./gradlew build

      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v4.3.1
        with:
          name: SonarQubeDemo2.apk
          path: app/build/outputs/apk/debug/app-debug.apk

