name: AndroidBuild
on:
  pull_request:
    branches: [master]

  push:
    branches: [master]

jobs:
  build:
    name: AndroidBuild
    runs-on: windows-latest
    permissions: read-all
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.2
        with:
          fetch-depth: 0

      - name: Setup Java JDK
        uses: actions/setup-java@v4.2.1
        with:
          java-version: '17'
          distribution: 'adopt'

